INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (1, 'CO1007', 'Cấu trúc Rời rạc cho Khoa học Máy tính');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (2, 'CO2011', 'Mô hình hóa Toán học');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (3, 'MT1003', 'Giải tích 1');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (4, 'MT1005', 'Giải tích 2');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (5, 'MT1007', 'Đại số Tuyến tính');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (6, 'MT2013', 'Xác suất và Thống kê');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (7, 'CH1003', 'Hóa đại cương');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (8, 'PH1003', 'Vật lý 1');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (9, 'PH1007', 'Thí nghiệm Vật lý');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (10, 'SP1013', 'Kỹ năng Xã hội A (báo Chí)');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (11, 'SP1015', 'Kỹ năng Xã hội B (sân Khấu)');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (12, 'SP1017', 'Kỹ năng Xã hội C (Thanh Nhạc)');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (13, 'SP1019', 'Kỹ năng Xã hội D (Nhiếp Ảnh)');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (14, 'SP1021', 'Kỹ năng Xã hội E (dẫn Chương trình)');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (15, 'SP1023', 'Kỹ năng Xã hội F (nhảy Hiện đại)');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (16, 'SP1025', 'Kỹ năng Xã hội G (nhảy Đường phố)');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (17, 'SP1027', 'Kỹ năng Xã hội H (tư Duy phản Biện)');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (18, 'SP1045', 'Kỹ năng Xã hội I');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (19, 'SP1007', 'Pháp luật Việt Nam Đại cương');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (20, 'SP1031', 'Triết học Mác - Lênin');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (21, 'SP1033', 'Kinh tế Chính trị Mác - Lênin');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (22, 'SP1035', 'Chủ nghĩa Xã hội Khoa học');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (23, 'SP1037', 'Tư tưởng Hồ Chí Minh');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (24, 'SP1039', 'Lịch sử Đảng Cộng sản Việt Nam');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (25, 'SP1041', 'Kỹ năng mềm');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (26, 'LA1003', 'Anh văn 1');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (27, 'LA1005', 'Anh văn 2');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (28, 'LA1007', 'Anh văn 3');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (29, 'LA1009', 'Anh văn 4');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (30, 'CO1005', 'Nhập môn Điện toán');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (31, 'IM1013', 'Kinh tế học Đại cương');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (32, 'IM1023', 'Quản lý Sản xuất cho Kỹ sư');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (33, 'IM1025', 'Quản lý Dự án cho Kỹ sư');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (34, 'IM1027', 'Kinh tế Kỹ thuật');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (35, 'IM3001', 'Quản trị Kinh doanh cho Kỹ sư');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (36, 'CO2001', 'Kỹ năng Chuyên nghiệp cho Kỹ sư');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (37, 'CO1023', 'Hệ thống số');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (38, 'CO1027', 'Kỹ thuật Lập trình');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (39, 'CO2003', 'Cấu trúc Dữ liệu và Giải Thuật');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (40, 'CO2007', 'Kiến trúc Máy tính');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (41, 'CO2013', 'Hệ cơ sở Dữ liệu');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (42, 'CO2039', 'Lập trình Nâng cao');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (43, 'CO3101', 'Đồ án Tổng hợp - Hướng Trí tuệ Nhân tạo');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (44, 'CO3103', 'Đồ án Tổng hợp - hướng Công nghệ Phần mềm');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (45, 'CO3105', 'Đồ án Tổng hợp - Hướng Hệ thống Thông tin');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (46, 'CO3127', 'Đồ án tổng hợp - hướng kỹ thuật dữ liệu');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (47, 'CO3061', 'Nhập môn Trí tuệ Nhân tạo');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (48, 'CO3069', 'Mật mã và An ninh mạng');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (49, 'CO2017', 'Hệ điều hành');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (50, 'CO3001', 'Công nghệ Phần mềm');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (51, 'CO3005', 'Nguyên lý Ngôn ngữ Lập trình');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (52, 'CO3093', 'Mạng máy tính');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (53, 'CO2037', 'Mạch Điện - Điện tử');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (54, 'CCGDTC', 'Chứng chỉ Giáo Dục Thể Chất');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (55, 'MI1003', 'Giáo dục Quốc phòng');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (56, 'ENG_GE_2', 'Điều kiện tiếng Anh tốt nghiệp dạy và học bằng tiếng Anh');
INSERT INTO "subjects" ("id", "subject_code", "subject_name") VALUES (57, 'SA4001', 'Hoạt động sinh viên');
